export type ReferenceWorkflowInput = {
  runtime: "codex" | "claude-code" | string;
  statusColumns: Array<{
    name: string;
    role: "active" | "wait" | "terminal" | null;
  }>;
  projectId: string;
};

export function generateReferenceWorkflow(
  input: ReferenceWorkflowInput
): string {
  const lines: string[] = [];

  lines.push("# Reference WORKFLOW.md — gh-symphony");
  lines.push("# This file is a reference template for authoring WORKFLOW.md.");
  lines.push(
    "# AI agents reference this file (via the /gh-symphony skill) when designing WORKFLOW.md."
  );
  lines.push("# Do not edit this file directly.");
  lines.push("");
  lines.push("---");
  lines.push("");

  lines.push("# ═══ FRONT MATTER FIELD REFERENCE ═══");
  lines.push(
    "# All front matter fields supported by the gh-symphony parser are listed below."
  );
  lines.push("");

  lines.push("tracker:");
  lines.push("  kind: github-project");
  lines.push(`  project_id: ${input.projectId}`);
  lines.push("  state_field: Status");
  lines.push("");

  const activeColumns = input.statusColumns.filter((c) => c.role === "active");
  const waitColumns = input.statusColumns.filter((c) => c.role === "wait");
  const terminalColumns = input.statusColumns.filter(
    (c) => c.role === "terminal"
  );
  const firstActive = activeColumns[0];

  if (activeColumns.length > 0) {
    lines.push("  active_states:");
    for (const col of activeColumns) {
      lines.push(`    - ${col.name}`);
    }
  } else {
    lines.push("  active_states: [{active column names}]");
  }

  if (terminalColumns.length > 0) {
    lines.push("  terminal_states:");
    for (const col of terminalColumns) {
      lines.push(`    - ${col.name}`);
    }
  } else {
    lines.push("  terminal_states: [{terminal column names}]");
  }

  if (firstActive) {
    lines.push("  blocker_check_states:");
    lines.push(`    - ${firstActive.name}`);
  } else {
    lines.push("  blocker_check_states: [{first active state}]");
  }

  lines.push("");

  const agentCommand = resolveAgentCommand(input.runtime);
  const hookComment = resolveHookComment(input.runtime);
  lines.push("polling:");
  lines.push("  interval_ms: 30000");
  lines.push("");

  lines.push("workspace:");
  lines.push("  root: .runtime/symphony-workspaces");
  lines.push("");

  lines.push("hooks:");
  lines.push(`  after_create: hooks/after_create.sh  # ${hookComment}`);
  lines.push("  before_run: null");
  lines.push("  after_run: null");
  lines.push("  before_remove: null");
  lines.push("  timeout_ms: 60000");
  lines.push("");

  lines.push("agent:");
  lines.push("  max_concurrent_agents: 10");
  lines.push("  max_retry_backoff_ms: 30000");
  lines.push("  retry_base_delay_ms: 1000");
  lines.push("  max_turns: 20");
  lines.push("");

  lines.push("codex:");
  lines.push(`  command: ${agentCommand}`);
  lines.push("  read_timeout_ms: 5000");
  lines.push("  turn_timeout_ms: 3600000");
  lines.push("  stall_timeout_ms: 300000");
  lines.push("");

  lines.push("---");
  lines.push("");

  lines.push("# ═══ PROMPT BODY REFERENCE ═══");
  lines.push(
    "# GitHub Project adaptation of the Elixir Symphony reference prompt."
  );
  lines.push("");

  lines.push("## Status Map");
  lines.push("");
  lines.push("| Status | Role | Agent Action |");
  lines.push("| ------ | ---- | ------------ |");

  for (const col of input.statusColumns) {
    const roleLabel = col.role ?? "unset";
    const action = resolveRoleAction(col.role);
    lines.push(`| ${col.name} | ${roleLabel} | ${action} |`);
  }

  if (waitColumns.length > 0) {
    lines.push("");
    lines.push("**Wait States (awaiting PR review):**");
    for (const col of waitColumns) {
      lines.push(
        `- **${col.name}**: PR created. Awaiting human review. Agent is idle.`
      );
    }
  }

  lines.push("");

  lines.push("## Default Posture");
  lines.push("");
  lines.push(
    "1. This is an unattended orchestration session. Do not ask humans for follow-up tasks."
  );
  lines.push(
    "2. Exit early only for genuine blockers (missing required credentials or secrets)."
  );
  lines.push(
    '3. In your final message, report only completed work and blockers. Do not include "next steps".'
  );
  lines.push(
    "4. Do not modify the issue body for planning or progress-tracking purposes."
  );
  lines.push(
    "5. If the issue is in a terminal state, do nothing and exit immediately."
  );
  lines.push(
    "6. If you discover out-of-scope improvements, open a separate issue rather than expanding the current scope."
  );
  lines.push(
    "7. Keep all commits as logical units and follow conventional commit format."
  );
  lines.push("8. Do not make commits that break existing tests.");
  lines.push("9. Verify all existing tests pass before creating a PR.");
  lines.push("10. Create a workpad as an issue comment to track progress.");
  lines.push("11. Use the gh-project skill to manage issue status.");
  lines.push(
    "12. When a blocker is found, record it in an issue comment and transition the status appropriately."
  );
  lines.push(
    "13. Once your work is complete and the PR is merged, transition the issue to the Done state."
  );
  lines.push("");

  lines.push("## Related Skills");
  lines.push("");
  lines.push(
    "- **gh-project**: Manage GitHub Project v2 issue status and update fields"
  );
  lines.push(
    "- **commit**: Create logical-unit commits (conventional commit format)"
  );
  lines.push("- **push**: Push branch and sync with the remote repository");
  lines.push("- **pull**: Fetch latest changes and resolve conflicts");
  lines.push("- **land**: Create PR, request review, and handle merge");
  lines.push("");

  lines.push("## Step 0: Determine current state and route");
  lines.push("");
  lines.push(
    "Check the current issue state and route to the appropriate step:"
  );
  lines.push("");

  if (terminalColumns.length > 0) {
    const terminalNames = terminalColumns.map((c) => c.name).join(", ");
    lines.push(`- **${terminalNames}** → Exit immediately. Do nothing.`);
  }

  if (waitColumns.length > 0) {
    const waitNames = waitColumns.map((c) => c.name).join(", ");
    lines.push(`- **${waitNames}** → Go to Step 3 (handle awaiting review).`);
  }

  if (activeColumns.length > 0) {
    const activeNames = activeColumns.map((c) => c.name).join(", ");
    lines.push(
      `- **${activeNames}** → Go to Step 1 (start or continue execution).`
    );
  }

  lines.push(
    "- **Other states** → Log the unclear state in an issue comment and exit."
  );
  lines.push("");

  lines.push("## Step 1: Start/continue execution");
  lines.push("");
  lines.push(
    "1. Read the issue body and comments to understand current progress."
  );
  lines.push(
    "2. If an existing workpad comment is found, continue from it; otherwise create a new workpad."
  );
  lines.push(
    "3. See the 'Workpad Template' section below for the workpad format."
  );
  lines.push(
    "4. If no branch exists, create a feature branch based on `{issue.repository}`."
  );
  lines.push("5. Proceed to Step 2.");
  lines.push("");

  lines.push("## Step 2: Execution phase");
  lines.push("");
  lines.push("1. Implement according to the issue description.");
  lines.push(
    "2. Commit changes in logical units (conventional commit format)."
  );
  lines.push("3. Verify all existing tests pass.");
  lines.push("4. Write tests for new functionality.");
  lines.push("5. Once all Completion Bar criteria are met, create a PR.");
  lines.push(
    "6. After creating the PR, transition the issue status to the Human Review state."
  );
  lines.push("7. Proceed to Step 3.");
  lines.push("");

  lines.push("## Step 3: Human Review and merge handling");
  lines.push("");
  lines.push("1. If a PR already exists, check for review comments.");
  lines.push(
    "2. If no review comments are present, remain in the waiting state."
  );
  lines.push(
    "3. If the PR is merged, transition the issue to a terminal state."
  );
  lines.push("4. If review changes are requested, proceed to Step 4.");
  lines.push("");

  lines.push("## Step 4: Rework handling");
  lines.push("");
  lines.push(
    "1. Read all PR review comments and identify the requested changes."
  );
  lines.push(
    "2. Process the changes following the PR Feedback Sweep Protocol."
  );
  lines.push("3. After implementing changes, commit and update the PR.");
  lines.push("4. Transition the issue status back to the Human Review state.");
  lines.push("5. Return to Step 3.");
  lines.push("");

  lines.push("## PR Feedback Sweep Protocol");
  lines.push("");
  lines.push("Order for processing PR review feedback:");
  lines.push("");
  lines.push(
    "1. **Collect all comments**: List all unresolved review comments."
  );
  lines.push(
    "2. **Triage by priority**: Handle blocking comments before non-blocking ones."
  );
  lines.push(
    "3. **Implement changes**: Make the code changes corresponding to each comment."
  );
  lines.push(
    "4. **Reply to comments**: Respond to each review comment with a description of what was done."
  );
  lines.push(
    "5. **Commit**: Commit changes in `fix: address PR review feedback` format."
  );
  lines.push("6. **Request re-review**: Ask the reviewer for a re-review.");
  lines.push("");

  lines.push("## Completion Bar");
  lines.push("");
  lines.push("All of the following must be satisfied before creating a PR:");
  lines.push("");
  lines.push(
    "- [ ] All requirements from the issue description are implemented."
  );
  lines.push("- [ ] All existing tests pass.");
  lines.push("- [ ] Tests are written for new functionality.");
  lines.push("- [ ] Code style follows project conventions.");
  lines.push("- [ ] The PR description clearly explains the changes.");
  lines.push("- [ ] Related documentation is updated (if applicable).");
  lines.push("");

  lines.push("## Guardrails");
  lines.push("");
  lines.push("- **Scope**: Never make changes outside the scope of the issue.");
  lines.push(
    "- **Secrets**: Never hardcode tokens, passwords, or API keys in code."
  );
  lines.push(
    "- **Breaking changes**: Do not modify existing APIs or interfaces without explicit authorization."
  );
  lines.push("- **Force push**: Do not force-push to the main/master branch.");
  lines.push(
    "- **Issue body**: Do not modify the issue body for progress tracking."
  );
  lines.push(
    "- **Infinite loops**: If the same task fails 3 or more consecutive times, log it as a blocker and exit."
  );
  lines.push("");

  lines.push("## Workpad Template");
  lines.push("");
  lines.push("Workpad format to create as an issue comment:");
  lines.push("");
  lines.push("```markdown");
  lines.push("## Workpad — {issue.identifier}");
  lines.push("");
  lines.push("**Status**: {current phase}");
  lines.push("**Branch**: {branch name}");
  lines.push("**PR**: {PR URL or not created}");
  lines.push("");
  lines.push("### Plan");
  lines.push("");
  lines.push("- [ ] {task 1}");
  lines.push("- [ ] {task 2}");
  lines.push("");
  lines.push("### Progress Log");
  lines.push("");
  lines.push("- {timestamp}: {action taken}");
  lines.push("");
  lines.push("### Blockers");
  lines.push("");
  lines.push("None");
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}

function resolveAgentCommand(runtime: string): string {
  switch (runtime) {
    case "codex":
      return "codex app-server";
    case "claude-code":
      return "claude-code";
    default:
      return runtime;
  }
}

function resolveHookComment(runtime: string): string {
  switch (runtime) {
    case "codex":
      return "npm/yarn/pnpm install script";
    case "claude-code":
      return "npm/yarn/pnpm install script";
    default:
      return "package-manager-specific script";
  }
}

function resolveRoleAction(
  role: "active" | "wait" | "terminal" | null
): string {
  switch (role) {
    case "active":
      return "Agent starts work immediately. Creates workpad and proceeds with implementation.";
    case "wait":
      return "PR created. Awaiting human review. Agent is idle.";
    case "terminal":
      return "Completed state. Agent exits.";
    case null:
      return "Role unset. Must be explicitly configured in WORKFLOW.md.";
  }
}
