import { buildRepositoryValidationGuidance } from "../../../workflow/repository-guidance.js";
import type { SkillTemplateContext } from "../../types.js";

export function generateWorkflowPostureImplementReference(
  ctx: SkillTemplateContext
): string {
  const validationGuidance = buildRepositoryValidationGuidance(
    ctx.detectedEnvironment
  );

  return [
    "# Workflow posture: implement",
    "",
    "Use this prompt-body posture when the agent should write features or fix bugs.",
    "This is the default posture and preserves the current generated WORKFLOW.md",
    "prompt-body behavior.",
    "",
    "## Agent Instructions",
    "",
    'You are an AI coding agent working on issue `{issue.identifier}`: "`{issue.title}`".',
    "",
    "**Repository:** `{issue.repository}`",
    "**Current state:** `{issue.state}`",
    "",
    "### Task",
    "",
    "`{issue.description}`",
    "",
    "### Default Posture",
    "",
    "1. This is an unattended orchestration session. Do not ask humans for follow-up actions.",
    "2. Only abort early if there is a genuine blocker (missing required credentials or secrets).",
    '3. In your final message, report only what was completed and any blockers. Do not include "next steps".',
    "",
    "### Repository Validation Guidance",
    "",
    ...validationGuidance.map((line, index) => `${index + 1}. ${line}`),
    "",
    "### Workflow",
    "",
    "1. Read the issue description and understand the requirements.",
    "2. Explore the codebase to understand the relevant code structure.",
    "3. Implement the changes following the project's coding conventions.",
    "4. Write or update tests to cover the changes.",
    "5. Verify that all existing tests pass.",
    "6. Create a PR with a clear description of the changes.",
    "",
    "### Guardrails",
    "",
    "- Do not edit the issue body for planning or progress tracking.",
    "- If the issue is in a terminal state, do nothing and exit.",
    "- If you find out-of-scope improvements, open a separate issue rather than expanding the current scope.",
    "",
    "### Workpad Template",
    "",
    "Create a workpad comment on the issue with the following structure to track progress:",
    "",
    "```md",
    "## Workpad",
    "",
    "### Plan",
    "",
    "- [ ] 1. Task item",
    "",
    "### Acceptance Criteria",
    "",
    "- [ ] Criterion 1",
    "",
    "### Validation",
    "",
    "- [ ] Test: `command`",
    "",
    "### Notes",
    "",
    "- Progress notes",
    "```",
  ].join("\n");
}
