/** Independent peer messages: literals, not generated by the schemas under test. */
import type {
  AgentEnvelope,
  CommandRecord,
  ObservationRequest,
  PollResponse,
  EnrollmentRequest,
  EnrollmentResponse,
  SessionRequest,
  SessionResponse,
  ResultRequest,
  ClaimResponse,
  EnvironmentRecord,
  ReadSelection,
  AggregateProject,
} from "../src/contracts.js";
export const environmentId = "11111111-1111-4111-8111-111111111111";
export const otherEnvironmentId = "22222222-2222-4222-8222-222222222222";
export const sessionId = "33333333-3333-4333-8333-333333333333";
export const projectId = "44444444-4444-4444-8444-444444444444";
export const agentId = "55555555-5555-4555-8555-555555555555";
export const requestId = "66666666-6666-4666-8666-666666666666";
export const commandId = "77777777-7777-4777-8777-777777777777";
export const time = "2026-10-05T00:00:00.000Z";
export const envelope = {
  protocolVersion: 1,
  environmentId,
  sessionId,
  requestId,
} satisfies AgentEnvelope;
export const enrollment = {
  protocolVersion: 1,
  requestId,
  token: "fixture-only-enrollment",
} satisfies EnrollmentRequest;
export const enrolled = {
  protocolVersion: 1,
  requestId,
  environmentId,
  agentId,
  credential: "fixture-only-credential",
} satisfies EnrollmentResponse;
export const session = {
  protocolVersion: 1,
  requestId,
  environmentId,
  agentId,
  agentVersion: "1.1.0",
  host: { hostname: "fixture-host", os: "linux" },
} satisfies SessionRequest;
export const opened = {
  ...envelope,
  expiresAt: "2026-10-05T00:10:00Z",
} satisfies SessionResponse;
export const observation = {
  ...envelope,
  sequence: 0,
  observedAt: time,
  inventory: {
    revisionId: "88888888-8888-4888-8888-888888888888",
    pageIndex: 0,
    pageCount: 1,
    projects: [
      {
        projectId,
        localProjectId: "project-folder-hash",
        displayName: "Prepared project",
        canonicalPath: "/home/operator/project",
        cliVersion: "1.1.0",
        validation: { state: "valid" },
        process: {
          state: "running",
          observedAt: time,
          identity: "native-start-identity",
          pid: 42,
        },
        observedAt: time,
        snapshot: { health: "healthy", summary: { activeRuns: 1 } },
        snapshotObservedAt: time,
        runs: [
          {
            runId: "local-run-1",
            status: "running",
            startedAt: time,
            updatedAt: time,
          },
        ],
      },
    ],
  },
} satisfies ObservationRequest;
export const accepted = {
  commandId,
  projectId,
  environmentId,
  localProjectId: "project-folder-hash",
  sessionId,
  operation: "stop",
  actor: "local-owner",
  idempotencyKey: "fixture-stop",
  submittedAt: time,
  expiresAt: "2026-10-05T00:00:30Z",
  state: "accepted",
} satisfies CommandRecord;
export const executing = {
  ...accepted,
  state: "executing",
  claimedAt: "2026-10-05T00:00:20Z",
  owner: { agentId, sessionId },
} satisfies CommandRecord;
export const unknown = {
  ...executing,
  state: "unknown",
  evidence: { effectStarted: true, targetIdentity: "native-start-identity" },
  diagnostic: { code: "process_unverified", message: "Exit not yet verified" },
} satisfies CommandRecord;
export const closedUnknown = {
  ...unknown,
  closure: {
    closedAt: "2026-10-05T00:02:00Z",
    actor: "local-owner",
    reason: "Inspected host; outcome remains uncertain",
  },
} satisfies CommandRecord;
export const claimReplay = {
  ...envelope,
  command: executing,
} satisfies ClaimResponse;
export const poll = {
  ...envelope,
  commands: [
    {
      commandId,
      projectId,
      environmentId,
      localProjectId: "project-folder-hash",
      sessionId,
      operation: "stop",
      actor: "local-owner",
      idempotencyKey: "fixture-stop",
      submittedAt: time,
      expiresAt: "2026-10-05T00:00:30Z",
    },
  ],
  reads: [
    {
      readId: "99999999-9999-4999-8999-999999999999",
      projectId,
      localProjectId: "project-folder-hash",
      sessionId,
      submittedAt: time,
      expiresAt: "2026-10-05T00:00:30Z",
      selection: {
        kind: "log-chunk",
        runId: "local-run-1",
        stream: "worker",
        maxBytes: 262144,
      },
    },
  ],
} satisfies PollResponse;
export const result = {
  ...envelope,
  result: {
    kind: "command",
    commandId,
    state: "unknown",
    observedAt: time,
    evidence: { targetIdentity: "native-start-identity", effectStarted: true },
    diagnostic: {
      code: "process_unverified",
      message: "Original process cannot be verified",
    },
  },
} satisfies ResultRequest;
export const awaiting = {
  environmentId,
  name: "Fixture host",
  enrollment: "enrolled",
  connection: "awaiting-signal",
} satisfies EnvironmentRecord;
export const logSelection = {
  kind: "log-chunk",
  runId: "local-run-1",
  stream: "worker",
  maxBytes: 262144,
} satisfies ReadSelection;
export const aggregate = {
  environmentId,
  projectId,
  localProjectId: "project-folder-hash",
  managed: true,
  connection: "online",
  lastReceivedAt: time,
  observation: observation.inventory.projects[0],
} satisfies AggregateProject;
