#!/usr/bin/env bash
set -euo pipefail

: "${SYMPHONY_REPOSITORY_CLONE_URL:?SYMPHONY_REPOSITORY_CLONE_URL is required}"
: "${SYMPHONY_REPOSITORY_PATH:?SYMPHONY_REPOSITORY_PATH is required}"
: "${SYMPHONY_ASSIGNED_BRANCH:?SYMPHONY_ASSIGNED_BRANCH is required}"

git clone --filter=blob:none "$SYMPHONY_REPOSITORY_CLONE_URL" "$SYMPHONY_REPOSITORY_PATH"
git -C "$SYMPHONY_REPOSITORY_PATH" checkout -B "$SYMPHONY_ASSIGNED_BRANCH" \
  "origin/${SYMPHONY_BASE_BRANCH:-HEAD}"
